### ISSUE TITLE
Certificate renewal not working

### ISSUE THREAD

**Issue by fidelix** [jc21/nginx-proxy-manager#109]
This is on the docker log:

```
[2019-3-25] [14:34:19] [IP Ranges] › ℹ info Fetching IP Ranges from online services...
[2019-3-25] [14:34:19] [IP Ranges] › ℹ info Fetching https://ip-ranges.amazonaws.com/ip-ranges.json
[2019-3-25] [14:34:19] [IP Ranges] › ℹ info Fetching https://www.cloudflare.com/ips-v4
[2019-3-25] [14:34:20] [IP Ranges] › ℹ info Fetching https://www.cloudflare.com/ips-v6
[2019-3-25] [14:34:20] [SSL ] › ℹ info Let's Encrypt Renewal Timer initialized
[2019-3-25] [14:34:20] [IP Ranges] › ℹ info IP Ranges Renewal Timer initialized
[2019-3-25] [14:34:20] [Global ] › ℹ info PID 1470 listening on port 8181 ...
[2019-3-25] [14:35:10] [Nginx ] › ℹ info Reloading Nginx
```

And yet some of my certificates have expired days ago.

![screenshot](https://i.imgur.com/QFhkwqC.png)

Would be nice to have the option to manually renew as well for these cases...

**Comment by jc21** [comment]
Do you have logs from the last 2 days or so? the renewal timer should fire every 12 hours and there should be some information in the docker logs, starting with `Renewing SSL certs close to expiry...`

And yes I agree a manual renewal would be nice too

**Comment by albertquiroga** [comment]
Experiencing a similar issue here... just to clarify when should the renewal timer? By 'every 12 hours' you mean at 12:00 and 24:00 or 12 hours after startup?

**Comment by jc21** [comment]
12 hours after startup. If you wanted to manually do it once, try a command like this:

```bash
docker exec -ti name_of_docker_container /usr/bin/certbot renew
```

**Comment by zaywalker** [comment]
I have same problem. but just UI shows wrong expired date, SSL is actually renewed and working. This means npm UI shows expired date but when I'm browsing SSLed site and check certificates, they shows renewed date. I'm not sure it's only my cases...

**Comment by jc21** [comment]
Ok yep sounds like a small bug there then.

**Comment by jc21** [comment]
The UI for this should be fixed in 2.0.13, just released. However in saying that, things still might not work as it should for those who have deleted any LE certs from within this application. The deletion was previously only revoking the certificate, not also deleting it from disk, so the auto renewal process was returning a non-zero response as a failure despite being able to renew all the other valid certificates.

If you find that after 1 hour of using 2.0.13 that the certificates list expiry still doesn't match the actual certificate date in the browser bar, then do the following:

- enter the docker container, ie: `docker exec -ti nginx-proxy-manager_app_1 bash`
- try to renew all the certs manually: `certbot renew`
- look for any messages about being unable to renew a certificate and then for each of them: `cerbot delete --cert-name npm-123`
- if you need a list of the certs: `certbot certificates`
- run `certbot renew` again until there are no errors, then wait up to an hour to see the new dates in the UI

**Comment by fidelix** [comment]
For those reading, don't follow the steps above. You will break your installation.

Nginx will fail to start as soon as you run the delete command in any certs and you will be forced to manually find and fix any references to it.

Unfortunately the solution I had to take was to delete the entries from the UI and add them again. It was a lot of work as I had about 50 domains with wildly different configurations.

To @jc21, this is still broken, even after 2.0.13, just so you know. My certificates have not renewed at all even after doing what I said above.

**Comment by nin9s** [comment]
@fidelix I'm still experiencing this behavior. Did you ever find a solution?

**Comment by fidelix** [comment]
@nin9s no. As I said I had to rebuild everything from scratch.
New versions seem to be behaving better, though, and I only encountered a similar issues once since I opened this issue.
