### ISSUE TITLE
Certbot-dns-cloudflare wrong version ?

### ISSUE THREAD

**Issue by MattXcz** [jc21/nginx-proxy-manager#1325]
`app_1  | ERROR: Could not find a version that satisfies the requirement certbot-dns-cloudflare==1.8.0 (from versions: none)
app_1  | ERROR: No matching distribution found for certbot-dns-cloudflare==1.8.0`

**Command failed: pip install certbot-dns-cloudflare==1.8.0 cloudflare**

I think it should be version 1.18.0, right ?
https://pypi.org/project/certbot-dns-cloudflare/

**Comment by MattXcz** [comment]
`app_1  | WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f5940deaa20>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/certbot-dns-cloudflare/
app_1  | ERROR: Could not find a version that satisfies the requirement certbot-dns-cloudflare==1.8.0 (from versions: none)
app_1  | ERROR: No matching distribution found for certbot-dns-cloudflare==1.8.0
`

**Comment by chaptergy** [comment]
The dns challenge plugins are fixed at a specific version to prevent breaking changes from breaking the integration. However this is not the issue you are encountering, it seems it was simply not able to connect to the package repository. I assume the problem should no longer exist and it should now be able to install it, since I am able to install it on my machine. If this is still an issue, please tag me and I can reopen this issue.

**Comment by chaptergy** [comment]
If the issue still persists you might be interested in https://github.com/jc21/nginx-proxy-manager/issues/1365 and the following comments

**Comment by S1M8N** [comment]
Hey @chaptergy !

For me the problem persist on my nginx proxy manager docker install. 2021.10.10

Do you have an idea how can I resolve this problem ?

Thank you in advanced

**Comment by kragil** [comment]
CommandError: WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError(': Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/cloudflare/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError(': Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/cloudflare/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError(': Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/cloudflare/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError(': Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/cloudflare/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError(': Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/cloudflare/
ERROR: Could not find a version that satisfies the requirement cloudflare (from versions: none)
ERROR: No matching distribution found for cloudflare

    at /app/lib/utils.js:16:13
    at ChildProcess.exithandler (node:child_process:430:5)
    at ChildProcess.emit (node:events:518:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
