### ISSUE TITLE
rewrite directive is no longer working

### ISSUE THREAD

**Issue by fariszr** [jc21/nginx-proxy-manager#1584]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes 
- Have you searched for similar issues (both open and closed)?
  - Yes 

**Describe the bug**

the rewrite directive has no effect when put into the advanced tab
for example  
`rewrite ^/about$ /preferences last;`
this works on LSIO SWAG, but doesn't work on NPM.

this issue started around the beginning of November, maybe something changed in OpenResty ? or a regression in v2.9.11+ ?

**Nginx Proxy Manager Version**

v2.9.12

**To Reproduce**
1. Go to 'any proxy host'
2. Click on 'advanced'
3. put a rewrite directive like `rewrite ^/about$ /preferences last;`
4. test it and it won't work.

**Expected behavior**

the rewrite directive should work, and rewrite URLs as instructed. 

**Screenshots**

**Operating System**

Debian 11/docker

**Additional context**

**Comment by chaptergy** [comment]
I'm 90% certain this is due to the variables introduced for the `proxy_pass` a while ago. But due to other issues this introduced as well, it has been [reverted](https://github.com/jc21/nginx-proxy-manager/pull/1578). So this should be fixed when the next release comes. You can watch this repo at the top of the page to get notified when a new release is published. If your issue is not resolved in the next version, please comment on this issue again, and I will reopen it.

**Comment by fariszr** [comment]
Any ETA on the next release ?

-------- Original Message --------

**Comment by chaptergy** [comment]
No, since there have not been any other changes since the previous version it might still take some time. You could also use this docker image while waiting for the new version: `jc21/nginx-proxy-manager:github-pr-1578`

**Comment by fariszr** [comment]
i just tested the PR version, there is no difference, it still doesn't work.

i removed and added the proxy host again to make sure that the config file was reloaded

**Comment by fariszr** [comment]
i just tried it with a new installation, same result.

**Comment by diwu1989** [comment]
Tried on the `github-pr-1578` image and rewrites also dont work.
I have a wss custom location that sends `/ws` to a different port, and need to rewrite `/ws` to root `/`

**Comment by diwu1989** [comment]
From looking at the template, it looks like `$forward_path` get set into `proxy_pass` before any advanced location sections are added at the bottom of the template.

Wouldn't any rewrite rule need to be included at the very top?

**Comment by fariszr** [comment]
> From looking at the template, it looks like `$forward_path` get set into `proxy_pass` before any advanced location sections are added at the bottom of the template.
> 
> Wouldn't any rewrite rule need to be included at the very top?
To test it out

You can edit the configs manually inside the container.
Configs are located at /data/nginx just install nano and edit them.

Edit the config and then restart the container and changes should apply.

**Comment by brtwrst** [comment]
Can we please get a release for this?
Custom locations are completely broken for me and editing the settings manually every time does get old quick.

**Comment by fariszr** [comment]
> Can we please get a release for this? Custom locations are completely broken for me and editing the settings manually every time does get old quick.

rewrites seem to work if you put the directive inside a location

for example

```
location /ex {
   rewrite ^/ex$ /page last; 
}
```

**Comment by fariszr** [comment]
this is still not fixed btw.

and the work around i posted earlier doesn't always work

**Comment by brtwrst** [comment]
This seems fixed now.
I re-saved the configs that have custom locations and they all worked without having to manually edit the config files.

**Comment by chaptergy** [comment]
Great to hear, thanks for the feedback!

**Comment by fariszr** [comment]
I still can't get it to work. even on the latest release.
i tried it with `rewrite ^/test$ /new last;`

**Comment by timdonovanuk** [comment]
This was working, then I updated to the latest version, and it's broken again.

**Comment by brtwrst** [comment]
Can confirm that my custom locations are breaking after editing and re-saving. with the current :latest version
