### ISSUE TITLE
"Bad Gateway" at Login Page after Upgrading to 2.7.0

### ISSUE THREAD

**Issue by Vocta1310** [jc21/nginx-proxy-manager#727]
Hi, I can't login anymore in configuration Panel after Upgrading to 2.7.0.
Before the Upgrade everything works great.

What can I do to fix this issue?

**Comment by jmeinicke** [comment]
my solution was to add the database env to my compose file

`   environment:
      # These are the settings to access your db
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
`

**Comment by Havoc85** [comment]
Having the exact same Problem.

I'm using SQLite. Are there anywhere examples what database environment variables I have to add to my compose file and what removing the config.json fiel from mount into container means?

**Comment by Vocta1310** [comment]
Fixed with 2.7.1 - Thank You @jc21

**Comment by Havoc85** [comment]
Fixed also on my side with 2.7.1 :-). Thank you @jc21 .

**Comment by 2Ben** [comment]
Seems not fixed for me on 2.7.1. I just did a docker pull to upgrade, should I do something else?

**Comment by stavros-k** [comment]
Does the container auto updates? I pulled new image, restarted the container but i'm still on 2.6.2

**Comment by Vocta1310** [comment]
@stavros-k - have you cleared your Browser Cache? Maybe that wrong information is stored in the cache ;)

**Comment by stavros-k** [comment]
> @stavros-k - have you cleared your Browser Cache? Maybe that wrong information is stored in the cache ;)

Didn't think of that. But i just tried from incognito and still says 2.6.2

**Comment by Havoc85** [comment]
> Didn't think of that. But i just tried from incognito and still says 2.6.2

I don't know if that was the question, but here a little insight of what I'm doing to update the nginx-proxy-manager docker container:
```
docker pull jc21/nginx-proxy-manager:latest
docker stop <id or name>
docker-compose up -d
```
Afterwards you can remove (all) old images with `docker image prune -f`

That's it. At least, if you're using docker-compose and if you're using "`image: jc21/nginx-proxy-manager:latest`" in it.

Hopefully that helps.

**Comment by stavros-k** [comment]
> > Didn't think of that. But i just tried from incognito and still says 2.6.2
> 
> I don't know if that was the question, but here a little insight of what I'm doing to update the nginx-proxy-manager docker container:
> 
> ```
> docker pull jc21/nginx-proxy-manager:latest
> docker stop <id or name>
> docker-compose up -d
> ```
> 
> Afterwards you can remove (all) old images with `docker image prune -f`
> 
> That's it. At least, if you're using docker-compose and if you're using "`image: jc21/nginx-proxy-manager:latest`" in it.
> 
> Hopefully that helps.

I'm on Unraid, so most of it its through GUI, but
i removed the docker (its like docker rm)
i did docker imager prune
re"installed" docker (its like docker run) (as repository i have jc21/nginx-proxy-manager but on docker run it says its pulling from :latest)
It didn't find available image so it pulled ALL layers from scratch.

On WebGUI it still says 2.6.2. Is there some way to check from console? 
Maybe something in my config isn't compatible with 2.7.1 yet and this keeps it from upgrading?

**Comment by MGoeppl** [comment]
2.7.1 works again for me ;)

**Comment by jc21** [comment]
It's very strange that the UI would report a different version than the one running in your docker instance. Perhaps hit the API directly with a command like this:

```bash
curl http://yournpmhost:81/api
```

and see what the version number being reported is. If it's not the one you're expecting then you definitely have the wrong image running. If it's different to the UI, then maybe the browser is aggressively caching however there is code in the frontend to reload the page if the backend version is different than the one the UI was expecting.

If you are using NPM to proxy the NPM admin site itself (as most of us do) you will want to make sure the Cache Assets option is not selected.

**Comment by stavros-k** [comment]
> It's very strange that the UI would report a different version than the one running in your docker instance. Perhaps hit the API directly with a command like this:
> 
> ```shell
> curl http://yournpmhost:81/api
> ```
> 
> and see what the version number being reported is. If it's not the one you're expecting then you definitely have the wrong image running. If it's different to the UI, then maybe the browser is aggressively caching however there is code in the frontend to reload the page if the backend version is different than the one the UI was expecting.
> 
> If you are using NPM to proxy the NPM admin site itself (as most of us do) you will want to make sure the Cache Assets option is not selected.

Ok, now i feel very **stupid** -.- I'm on Unraid and i'm using the templates there. which is a different image "jlesage/nginx-proxy-manager" i was seeing the "j" in the start and the "nginx-proxy-manager" after and i was like "yea this is ok" 
I'll have either to wait until this image is updated, or try to convert your docker-compose to plain docker, or install portainer
Unraid doesn't support docker-compose natively,

**Comment by LivingWithHippos** [comment]
I had this issue after moving the variables to the compose file and removing `config.json`. 
As jmeinicke said the solution was removing from the docker compose the line mounting the file

```yaml
    volumes:
      - ./config.json:/app/config/production.json
```

**Comment by mwip** [comment]
I can confirm that is is still an issue with 2.7.1. 

Rocking a Raspberry pi and just did a 
```
sudo docker-compose down
sudo docker-compose pull
sudo docker-compose up -d
```

The proxy works just fine, but I cannot login.

**Comment by anselal** [comment]
@mwip I get the same error on my RPi2.

**Comment by roswitina** [comment]
I use a Helios64 with an arm64 board. The Docker image starts correctly, but the first time I login with the data admin@example.com/changeme I get the message "Bad Gateway".

The login page shows version 2.7.1.

**Comment by anselal** [comment]
I used version 2 on my docker-compose.yml and it worked

**Comment by dkupper76** [comment]
I just installed version 2.7.3, my first time using this, and I am having the same issues, login fails, and I get the "Bad Gateway" message.  

Also, @jmeinicke mentioned the website:  https://nginxproxymanager.com/setup/, but when I try to visit that website, I get the following error message from Firefox:

Secure Connection Failed

An error occurred during a connection to nginxproxymanager.com. SSL received a record that exceeded the maximum permissible length.

Error code: SSL_ERROR_RX_RECORD_TOO_LONG


Can you please help?

Thanks in advance.

**Comment by dkupper76** [comment]
I forgot to add, I just looked at this in Portainer, and I see Container Unhealthy, and looking further I see the following error shown in Portainer:

"parse error: Invalid numeric literal at line 1, column 7 NOT OK"

I have not dug any deeper into that, but I thought I would mention it, because perhaps these issues are related.

Thanks in advance.

**Comment by dkupper76** [comment]
I tried downgrading to version 2.7.1, which somebody said was working, but I still get the same issue, and it actually shows up as version 2.7.2. The Website : https://nginxproxymanager.com/setup/, is still having certificate errors, and I can't visit it, so I opened a new issue on the website cert errors

**Comment by dkupper76** [comment]
I solved the problem by deleting the folders on the Host Machine running Docker, deleting the docker compose file and starting from scratch, not sure what caused my problem, but it appears to be working now.
