### ISSUE TITLE
Web Interface not working

### ISSUE THREAD

**Issue by Sigri44** [jc21/nginx-proxy-manager#731]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image? yes
- Are you sure you're not using someone else's docker image? yes

**Describe the bug**
- 
- A clear and concise description of what the bug is.
- What version of Nginx Proxy Manager is reported on the login page?

**To Reproduce**
1. Upgrade image from 2.6.1 to 2.7.1
2. Remove container
3. docker-compose up -d
4. Log in
5. Error and data is empty

**Expected behavior**
`javascript
TypeError: e[t] is undefined
    r http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:1
    showDashboard http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    promise callback*showDashboard http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    xe http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    i http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    Y http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    execute http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    route http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    loadUrl http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    F http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    loadUrl http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    start http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    onStart http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:3
    f http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    m http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    d http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    trigger http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    O http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    render http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    ae http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    show http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    onStart http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:3
    promise callback*onStart http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:3
    O http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    start http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    <anonymous> http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:293
    d http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    l http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    setTimeout handler*a/< http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    u http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    fireWith http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    fire http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    u http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    fireWith http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    ready http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    V http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    EventListener.handleEvent* http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    <anonymous> http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:16
    <anonymous> http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:16
    r http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:1
    <anonymous> http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:293
    r http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:1
    <anonymous> http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:1
    <anonymous> http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:1
main.bundle.js:1:1921
    oe http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:1
    (Asynchrone : promise callback)
    showDashboard http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    xe http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    i http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    Y http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    execute http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    route http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    loadUrl http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    F http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    loadUrl http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    start http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    onStart http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:3
    f http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    m http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    d http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    trigger http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    O http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    render http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    ae http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    show http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    onStart http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:3
    (Asynchrone : promise callback)
    onStart http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:3
    O http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    start http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    <anonyme> http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:293
    d http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    l http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    (Asynchrone : setTimeout handler)
    a http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    u http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    fireWith http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    fire http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    u http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    fireWith http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    ready http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    V http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    (Asynchrone : EventListener.handleEvent)
    <anonyme> http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    <anonyme> http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:16
    <anonyme> http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:16
    r http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:1
    <anonyme> http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:293
    r http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:1
    <anonyme> http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:1
    <anonyme> http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:1
`

`javascript
Uncaught (in promise) TypeError: e[t] is undefined
    r http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:1
    showDashboard http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    promise callback*showDashboard http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    xe http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    i http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    Y http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    execute http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    route http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    loadUrl http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    F http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    loadUrl http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    start http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    onStart http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:3
    f http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    m http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    d http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    trigger http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    O http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    render http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    ae http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    show http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    onStart http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:3
    promise callback*onStart http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:3
    O http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    start http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    <anonymous> http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:293
    d http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    l http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    setTimeout handler*a/< http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    u http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    fireWith http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    fire http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    u http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    fireWith http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    ready http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    V http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    EventListener.handleEvent* http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    <anonymous> http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:16
    <anonymous> http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:16
    r http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:1
    <anonymous> http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:293
    r http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:1
    <anonymous> http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:1
    <anonymous> http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:1
main.bundle.js:1:356
    oe http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:1
    (Asynchrone : promise callback)
    showDashboard http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    xe http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    i http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    Y http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    execute http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    route http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    loadUrl http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    F http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    loadUrl http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    start http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    onStart http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:3
    f http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    m http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    d http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    trigger http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    O http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    render http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    ae http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    show http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    onStart http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:3
    (Asynchrone : promise callback)
    onStart http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:3
    O http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    start http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    <anonyme> http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:293
    d http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    l http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    (Asynchrone : setTimeout handler)
    a http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    u http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    fireWith http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    fire http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    u http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    fireWith http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    ready http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    V http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    (Asynchrone : EventListener.handleEvent)
    <anonyme> http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:27
    <anonyme> http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:16
    <anonyme> http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:16
    r http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:1
    <anonyme> http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:293
    r http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:1
    <anonyme> http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:1
    <anonyme> http://192.168.1.74:81/js/main.bundle.js?v=2.7.1:1
`

**Screenshots**
![image](https://user-images.githubusercontent.com/9304947/99675587-abfea800-2a77-11eb-953a-047cad134b42.png)

**Operating System**
- Docker container on Linux/Proxmox

**Comment by shrunbr** [comment]
I had this same issue coming from 2.3.X on CentOS 8. I noticed that my login page displayed the wrong version but after login at the bottom it had the new version listed.

I was able to resolve by doing `docker-compose down` again and bringing everything back up with `docker-compose up -d`

Give it a shot? Hope it helps!

**Comment by jc21** [comment]
We're still not sure what causes this. People have found clearing the browser cache works even though nothing should be cached or at least if it is cached, it should be the correct code.

**Comment by Sigri44** [comment]
Nice, solved with : `sudo docker-compose down && sudo docker-compose up -d` again.

Thanks.

**Comment by sduensin** [comment]
It appears to be a caching problem.  I just recreated my container.  No luck.  Dumped all the cookies for my site and the problem remained.  Cleared my browser cache - works!
